# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler using RCPP
#' @description A random walk Metropolis sampler for the standard Laplace distribution using RCPP
#' @param sigma the standard deviation of normal distribution for the increment
#' @param x0 the origial position of the chain
#' @param N the number of generating times
#' @return a random sample for the standard Laplace distribution \code{n}
#' @examples
#' \dontrun{
#' N <- 2000
#' x0 <- 20
#' sigma <- 2
#' rwmC(sigma, x0, N)
#' }
#' @export
rwmC <- function(sigma, x0, N) {
    .Call('_SC19022_rwmC', PACKAGE = 'SC19022', sigma, x0, N)
}

